Repository AY2324S1-CS2113-T17-1/tp, pull requests merged in 2023-11, with the labels that each got.

#133 Update docs
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/images/HelpAddDiet.svg
  docs/images/Save.svg
  docs/puml/HelpAddDiet.puml
  docs/puml/Save.puml
Labels: priority.High, type.Task

#138 Implement Sleep Duration & Date Tracking with ISO Date Standardization and Search Feature
  docs/DeveloperGuide.md
  docs/README.md
  docs/images/SleepAndSleepListClassDiagram.svg
  docs/puml/Sleep/SleepAndSleeplistClassDiagram.puml
  src/main/java/athleticli/commands/sleep/AddSleepCommand.java
  src/main/java/athleticli/commands/sleep/DeleteSleepCommand.java
  src/main/java/athleticli/commands/sleep/EditSleepCommand.java
  src/main/java/athleticli/commands/sleep/FindSleepCommand.java
  src/main/java/athleticli/data/sleep/Sleep.java
  src/main/java/athleticli/data/sleep/SleepList.java
  src/main/java/athleticli/ui/Parser.java
  src/test/java/athleticli/commands/sleep/AddSleepCommandTest.java
  src/test/java/athleticli/commands/sleep/DeleteSleepCommandTest.java
  src/test/java/athleticli/commands/sleep/EditSleepCommandTest.java
  src/test/java/athleticli/commands/sleep/ListSleepCommandTest.java
  src/test/java/athleticli/data/sleep/SleepListTest.java
  src/test/java/athleticli/data/sleep/SleepTest.java
  src/test/java/athleticli/ui/ParserTest.java
  text-ui-test/EXPECTED.TXT
  text-ui-test/input.txt
Labels: type.Enhancement, Sleep

#139 Explain implementation of Activity Goal Tracking in DG
  docs/DeveloperGuide.md
  docs/DeveloperGuide/AddActivity.png
  docs/images/ActivityGoalEvaluation.svg
  docs/images/AddActivity.svg
  docs/images/AddActivityGoal.svg
  docs/puml/Activity.puml
  docs/puml/ActivityGoalEvaluation.puml
  docs/puml/AddActivity.puml
  docs/puml/AddActivityGoal.puml
Labels: priority.High, type.Task, Activity, Goal

#145 Refactor `parser` package
  src/main/java/athleticli/AthletiCLI.java
  src/main/java/athleticli/commands/HelpCommand.java
  src/main/java/athleticli/commands/diet/EditDietCommand.java
  src/main/java/athleticli/parser/ActivityParser.java
  src/main/java/athleticli/parser/CommandName.java
  src/main/java/athleticli/parser/DietParser.java
  src/main/java/athleticli/parser/NutrientVerifier.java
  src/main/java/athleticli/parser/Parameter.java
  src/main/java/athleticli/parser/Parser.java
  src/main/java/athleticli/parser/SleepParser.java
  src/main/java/athleticli/ui/Message.java
  src/main/java/athleticli/ui/Parser.java
  src/test/java/athleticli/commands/diet/EditDietCommandTest.java
  src/test/java/athleticli/parser/ActivityParserTest.java
  src/test/java/athleticli/parser/DietParserTest.java
  src/test/java/athleticli/parser/ParserTest.java
  src/test/java/athleticli/parser/SleepParserTest.java
  src/test/java/athleticli/ui/NutrientVerifierTest.java
  src/test/java/athleticli/ui/ParserTest.java
Labels: priority.Medium, type.Optimization

#146 Add parse and unparse for Diet class
  src/main/java/athleticli/data/diet/DietList.java
  src/test/java/athleticli/data/diet/DietListTest.java
Labels: priority.High, type.Story, Diet

#147 Standardise format for UG
  docs/UserGuide.md
Labels: type.Optimization

#150 Add the `Parser` component in DG
  docs/DeveloperGuide.md
  docs/README.md
Labels: priority.Medium, type.Task

#152 Userguide update, added sleep commands and command summary table
  docs/UserGuide.md
  docs/UserGuideTmp.md
Labels: type.Task

#153 Add newlines when saving items
  src/main/java/athleticli/data/StorableList.java
Labels: priority.Medium, type.Task

#157 Activity Storage Parsing
  docs/UserGuide.md
  src/main/java/athleticli/data/activity/Activity.java
  src/main/java/athleticli/data/activity/ActivityGoalList.java
  src/main/java/athleticli/data/activity/ActivityList.java
  src/main/java/athleticli/data/activity/Cycle.java
  src/main/java/athleticli/data/activity/Run.java
  src/main/java/athleticli/data/activity/Swim.java
  src/main/java/athleticli/parser/Parameter.java
  src/main/java/athleticli/ui/Message.java
  src/test/java/athleticli/data/activity/ActivityGoalListTest.java
  src/test/java/athleticli/data/activity/ActivityListTest.java
  text-ui-test/runtest.sh
Labels: priority.High, type.Task, Activity, Goal

#228 Move datetime formatters to common package
  src/main/java/athleticli/common/Config.java
  src/main/java/athleticli/data/activity/Activity.java
  src/main/java/athleticli/data/activity/ActivityGoalList.java
  src/main/java/athleticli/data/activity/ActivityList.java
  src/main/java/athleticli/data/diet/Diet.java
  src/main/java/athleticli/data/diet/DietGoalList.java
  src/main/java/athleticli/data/diet/DietList.java
  src/main/java/athleticli/data/sleep/Sleep.java
  src/main/java/athleticli/data/sleep/SleepGoalList.java
  src/main/java/athleticli/data/sleep/SleepList.java
Labels: type.Enhancement, Sleep, Diet, Activity

#235 Fix spacing in activity goal list
  src/main/java/athleticli/commands/activity/ListActivityCommand.java
  src/main/java/athleticli/commands/activity/ListActivityGoalCommand.java
  src/main/java/athleticli/data/activity/ActivityGoalList.java
  src/test/java/athleticli/commands/activity/ListActivityGoalCommandTest.java
Labels: severity.VeryLow, type.Bug, Activity, Goal

#237 Enable user to effectively edit activities with optional parameter choice + some UG updates
  docs/UserGuide.md
  src/main/java/athleticli/commands/activity/EditActivityCommand.java
  src/main/java/athleticli/data/activity/Activity.java
  src/main/java/athleticli/data/activity/ActivityChanges.java
  src/main/java/athleticli/data/activity/Cycle.java
  src/main/java/athleticli/data/activity/Run.java
  src/main/java/athleticli/data/activity/Swim.java
  src/main/java/athleticli/parser/ActivityParser.java
  src/main/java/athleticli/parser/Parameter.java
  src/main/java/athleticli/parser/Parser.java
  src/main/java/athleticli/ui/Message.java
  src/test/java/athleticli/commands/activity/EditActivityCommandTest.java
  src/test/java/athleticli/data/activity/ActivityTest.java
  src/test/java/athleticli/data/activity/CycleTest.java
  src/test/java/athleticli/data/activity/RunTest.java
  src/test/java/athleticli/data/activity/SwimTest.java
  src/test/java/athleticli/parser/ActivityParserTest.java
  text-ui-test/EXPECTED.TXT
  text-ui-test/input.txt
Labels: priority.Medium, type.Enhancement, Activity, Feature Flaw, Feature Suggestion

#242 Several bug fixes
  docs/UserGuide.md
  src/main/java/athleticli/commands/activity/EditActivityCommand.java
  src/main/java/athleticli/parser/ActivityParser.java
  src/main/java/athleticli/parser/Parser.java
  src/main/java/athleticli/ui/Message.java
  src/test/java/athleticli/commands/activity/EditActivityCommandTest.java
  text-ui-test/EXPECTED.TXT
Labels: priority.High, severity.Low, severity.Medium, severity.VeryLow, Activity, UG

#247 Fix TOC
  docs/UserGuide.md
Labels: type.Task

#249 Allow users to start from empty lists when invalid entries are detected
  src/main/java/athleticli/AthletiCLI.java
  src/main/java/athleticli/data/Data.java
  src/main/java/athleticli/ui/Message.java
Labels: priority.High, type.Task

#250 Implemented Sleep Goals and Sleep Storage functionality
  src/main/java/athleticli/commands/sleep/EditSleepGoalCommand.java
  src/main/java/athleticli/commands/sleep/ListSleepGoalCommand.java
  src/main/java/athleticli/commands/sleep/SetSleepGoalCommand.java
  src/main/java/athleticli/commands/sleep/ViewSleepGoalCommand.java
  src/main/java/athleticli/data/sleep/SleepGoal.java
  src/main/java/athleticli/data/sleep/SleepGoalList.java
  src/main/java/athleticli/data/sleep/SleepList.java
  src/main/java/athleticli/parser/CommandName.java
  src/main/java/athleticli/parser/Parser.java
  src/main/java/athleticli/parser/SleepParser.java
  src/main/java/athleticli/ui/Message.java
  src/test/java/athleticli/data/sleep/SleepListTest.java
  text-ui-test/EXPECTED.TXT
  text-ui-test/input.txt
Labels: priority.High, type.Bug, Sleep

#253 Add visual elements to UG and fix some bugs
  docs/UserGuide.md
  docs/images/AthletiCLI-Banner.png
  src/main/java/athleticli/commands/activity/ListActivityCommand.java
  src/main/java/athleticli/data/activity/Activity.java
  src/main/java/athleticli/data/activity/Cycle.java
  src/main/java/athleticli/data/activity/Run.java
  src/main/java/athleticli/data/activity/Swim.java
  src/main/java/athleticli/parser/ActivityParser.java
  src/main/java/athleticli/ui/Message.java
  src/test/java/athleticli/commands/activity/ListActivityCommandTest.java
  text-ui-test/EXPECTED.TXT
Labels: priority.Medium, severity.Low, Activity, UG

#258 Add draft PPP for skylee03
  docs/AboutUs.md
  docs/team/skylee03.md
Labels: priority.High, type.Task

#260 Generate initial draft of PPP
  docs/team/alwo223.md
Labels: priority.High, type.Task, PPP

#262 Improved some activity features
  docs/UserGuide.md
  docs/images/listActivityDetailedShowcase.png
  docs/images/listActivityShowcase.png
  src/main/java/athleticli/commands/activity/EditActivityCommand.java
  src/main/java/athleticli/commands/activity/SetActivityGoalCommand.java
  src/main/java/athleticli/data/activity/ActivityGoalList.java
  src/main/java/athleticli/ui/Message.java
  src/test/java/athleticli/commands/activity/SetActivityGoalCommandTest.java
  src/test/java/athleticli/data/activity/ActivityGoalListTest.java
Labels: priority.High, type.Bug, type.Enhancement, Activity, Goal, UG

#263 Delete Command and Portfolio Page
  docs/UserGuide.md
  docs/team/nihalzp.md
  src/main/java/athleticli/commands/activity/DeleteActivityGoalCommand.java
  src/main/java/athleticli/parser/ActivityParser.java
  src/main/java/athleticli/parser/CommandName.java
  src/main/java/athleticli/parser/DietParser.java
  src/main/java/athleticli/parser/Parser.java
  src/main/java/athleticli/ui/Message.java
  src/test/java/athleticli/parser/DietParserTest.java
  src/test/java/athleticli/parser/ParserTest.java
Labels: priority.High, type.Story, type.Task, Activity, UG, PPP

#264 Sleep standardization, bug fixing and other updates
  src/main/java/athleticli/commands/sleep/AddSleepCommand.java
  src/main/java/athleticli/commands/sleep/DeleteSleepCommand.java
  src/main/java/athleticli/commands/sleep/EditSleepCommand.java
  src/main/java/athleticli/commands/sleep/ListSleepCommand.java
  src/main/java/athleticli/data/sleep/Sleep.java
  src/main/java/athleticli/data/sleep/SleepList.java
  src/main/java/athleticli/parser/Parameter.java
  src/main/java/athleticli/parser/Parser.java
  src/main/java/athleticli/parser/SleepParser.java
  src/main/java/athleticli/ui/Message.java
  src/test/java/athleticli/commands/sleep/AddSleepCommandTest.java
  src/test/java/athleticli/commands/sleep/DeleteSleepCommandTest.java
  src/test/java/athleticli/commands/sleep/EditSleepCommandTest.java
  src/test/java/athleticli/commands/sleep/ListSleepCommandTest.java
  src/test/java/athleticli/data/sleep/SleepListTest.java
  src/test/java/athleticli/data/sleep/SleepTest.java
  text-ui-test/CommandTestCases/AddSleepAttack.txt
  text-ui-test/EXPECTED.TXT
Labels: Sleep

#265 Improve code quality
  src/main/java/athleticli/commands/activity/AddActivityCommand.java
  src/main/java/athleticli/commands/activity/DeleteActivityCommand.java
  src/main/java/athleticli/commands/activity/DeleteActivityGoalCommand.java
  src/main/java/athleticli/commands/activity/EditActivityCommand.java
  src/main/java/athleticli/commands/activity/ListActivityCommand.java
  src/main/java/athleticli/commands/activity/SetActivityGoalCommand.java
  src/main/java/athleticli/data/activity/Activity.java
  src/main/java/athleticli/data/activity/ActivityChanges.java
  src/main/java/athleticli/data/activity/ActivityGoal.java
  src/main/java/athleticli/data/activity/ActivityGoalList.java
  src/main/java/athleticli/data/activity/ActivityList.java
  src/main/java/athleticli/data/activity/Cycle.java
  src/main/java/athleticli/data/activity/Run.java
  src/main/java/athleticli/data/activity/Swim.java
  src/main/java/athleticli/parser/ActivityParser.java
  src/main/java/athleticli/parser/Parameter.java
  src/main/java/athleticli/ui/Message.java
  src/test/java/athleticli/data/activity/ActivityGoalListTest.java
  src/test/java/athleticli/data/activity/SwimTest.java
  src/test/java/athleticli/parser/ActivityParserTest.java
  text-ui-test/EXPECTED.TXT
Labels: priority.Medium, type.Optimization, Activity, Goal

#266 Add message in case of empty activity list and set boundary for elevation input
  src/main/java/athleticli/commands/activity/ListActivityCommand.java
  src/main/java/athleticli/parser/ActivityParser.java
  src/main/java/athleticli/ui/Message.java
Labels: priority.Medium, type.Enhancement, Activity

#271 Update sleep command syntax and examples
  docs/UserGuide.md
Labels: type.Bug, type.Enhancement, Sleep, UG

#273 More Tests and Bug Fixes for Diet, Activity Goal
  docs/UserGuide.md
  src/main/java/athleticli/commands/activity/DeleteActivityGoalCommand.java
  src/main/java/athleticli/commands/activity/EditActivityGoalCommand.java
  src/main/java/athleticli/commands/activity/ListActivityGoalCommand.java
  src/main/java/athleticli/commands/diet/AddDietCommand.java
  src/main/java/athleticli/commands/diet/DeleteDietCommand.java
  src/main/java/athleticli/commands/diet/EditDietCommand.java
  src/main/java/athleticli/commands/diet/FindDietCommand.java
  src/main/java/athleticli/commands/diet/ListDietCommand.java
  src/main/java/athleticli/common/Config.java
  src/main/java/athleticli/parser/ActivityParser.java
  src/main/java/athleticli/parser/DietParser.java
  src/main/java/athleticli/parser/Parser.java
  src/main/java/athleticli/ui/Message.java
  src/test/java/athleticli/commands/activity/DeleteActivityGoalCommandTest.java
  src/test/java/athleticli/commands/diet/FindDietCommandTest.java
  src/test/java/athleticli/parser/ActivityParserTest.java
  src/test/java/athleticli/parser/DietParserTest.java
  src/test/java/athleticli/parser/ParserTest.java
Labels: priority.High, severity.High, type.Bug, type.Enhancement, Diet, Activity, Goal, Find, UG

#274 Add Activity class diagram and sequence diagram for ActivityParsing process
  docs/DeveloperGuide.md
  docs/images/ActivityInheritance.svg
  docs/images/ActivityParsing.svg
  docs/puml/Activity.puml
  docs/puml/Activity/Activity.puml
  docs/puml/Activity/ActivityGoalEvaluation.puml
  docs/puml/Activity/ActivityParsing.puml
  docs/puml/Activity/AddActivity.puml
  docs/puml/Activity/AddActivityGoal.puml
Labels: priority.High, Activity, DG

#277 Prevent usage of edit commands for mismatching activity type
  docs/UserGuide.md
  src/main/java/athleticli/commands/activity/EditActivityCommand.java
  src/main/java/athleticli/parser/Parser.java
  src/main/java/athleticli/ui/Message.java
  src/test/java/athleticli/commands/activity/EditActivityCommandTest.java
Labels: priority.High, severity.High, type.Bug, type.Enhancement, Activity

#280 UG Updates
  docs/UserGuide.md
  docs/team/dadevchia.md
Labels: Sleep, Activity, UG

#282 DG updates in activity management and blocking of future dates and datetime
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/images/ActivityObjectDiagram.svg
  docs/puml/Activity/ActivityObjectDiagram.puml
  src/main/java/athleticli/parser/Parser.java
  src/main/java/athleticli/ui/Message.java
Labels: priority.High, type.Enhancement, Activity, Find

#281 Yi Cheng's PPP
  docs/team/yicheng.md
  src/main/java/athleticli/data/diet/DietGoalList.java
  src/test/java/athleticli/data/diet/DietGoalListTest.java
  src/test/java/athleticli/data/diet/DietGoalTest.java
Labels: priority.High, PPP

#283 Update skylee03's PPP
  docs/team/skylee03.md
Labels: priority.High, type.Task, PPP

#285 Improve test coverage for goals
  src/test/java/athleticli/data/GoalTest.java
Labels: priority.Medium, type.Task, Goal

#284 Improve test coverage for diet goals
  src/main/java/athleticli/data/diet/DietGoalList.java
  src/main/java/athleticli/parser/DietParser.java
  src/main/java/athleticli/parser/Parameter.java
  src/main/java/athleticli/parser/Parser.java
  src/test/java/athleticli/commands/diet/EditDietGoalCommandTest.java
  src/test/java/athleticli/commands/diet/SetDietGoalCommandTest.java
  src/test/java/athleticli/data/diet/DietGoalListTest.java
  src/test/java/athleticli/data/diet/DietGoalTest.java
  src/test/java/athleticli/parser/DietParserTest.java
Labels: type.Task, Diet

#288 User Guide Update and Numerous Bug Fix
  docs/UserGuide.md
  docs/images/listActivityGoalShowcase.png
  docs/images/listDietShowcase.png
  src/main/java/athleticli/commands/HelpCommand.java
  src/main/java/athleticli/common/Config.java
  src/main/java/athleticli/data/activity/Activity.java
  src/main/java/athleticli/data/diet/Diet.java
  src/main/java/athleticli/data/diet/DietList.java
  src/main/java/athleticli/data/sleep/Sleep.java
  src/main/java/athleticli/parser/DietParser.java
  src/main/java/athleticli/parser/Parser.java
  src/main/java/athleticli/ui/Message.java
  src/test/java/athleticli/commands/diet/AddDietCommandTest.java
  src/test/java/athleticli/commands/diet/DeleteDietCommandTest.java
  src/test/java/athleticli/commands/diet/ListDietCommandTest.java
  src/test/java/athleticli/data/diet/DietListTest.java
  src/test/java/athleticli/data/diet/DietTest.java
  src/test/java/athleticli/parser/DietParserTest.java
  src/test/java/athleticli/parser/ParserTest.java
  text-ui-test/EXPECTED.TXT
Labels: priority.High, severity.High, type.Bug, Diet, Activity, Goal, UG

#302 Update skylee03's PPP
  docs/team/skylee03.md
Labels: priority.Medium, type.Task

#296 Improve Sleep-related Commands and Data Classes
  src/main/java/athleticli/commands/sleep/AddSleepCommand.java
  src/main/java/athleticli/commands/sleep/DeleteSleepCommand.java
  src/main/java/athleticli/commands/sleep/EditSleepCommand.java
  src/main/java/athleticli/commands/sleep/EditSleepGoalCommand.java
  src/main/java/athleticli/commands/sleep/FindSleepCommand.java
  src/main/java/athleticli/commands/sleep/ListSleepCommand.java
  src/main/java/athleticli/commands/sleep/ListSleepGoalCommand.java
  src/main/java/athleticli/commands/sleep/SetSleepGoalCommand.java
  src/main/java/athleticli/data/sleep/Sleep.java
  src/main/java/athleticli/data/sleep/SleepGoal.java
  src/main/java/athleticli/data/sleep/SleepGoalList.java
  src/main/java/athleticli/data/sleep/SleepList.java
  src/main/java/athleticli/parser/SleepParser.java
  src/main/java/athleticli/ui/Message.java
  src/test/java/athleticli/commands/sleep/FindSleepCommandTest.java
  text-ui-test/CommandTestCases/AddSleepAttack.txt
  text-ui-test/EXPECTED.TXT
Labels: type.Bug, Sleep, type.Optimization

#304 Update activity command formats and apply some code standard improvements
  docs/UserGuide.md
  src/main/java/athleticli/commands/activity/EditActivityCommand.java
  src/main/java/athleticli/commands/activity/SetActivityGoalCommand.java
  src/main/java/athleticli/data/activity/Activity.java
  src/main/java/athleticli/data/activity/ActivityGoalList.java
  src/main/java/athleticli/data/activity/Cycle.java
  src/main/java/athleticli/data/activity/Run.java
  src/main/java/athleticli/data/activity/Swim.java
  src/main/java/athleticli/parser/ActivityParser.java
  src/main/java/athleticli/ui/Message.java
  text-ui-test/EXPECTED.TXT
Labels: priority.High, type.Optimization, Activity, UG

#316 Fix Invalid Leap Year Bug
  src/main/java/athleticli/common/Config.java
  src/test/java/athleticli/parser/ParserTest.java
Labels: severity.Low, Feature Flaw

#307 Update sleep duration units and help command messages
  src/main/java/athleticli/commands/HelpCommand.java
  src/main/java/athleticli/data/sleep/Sleep.java
  src/main/java/athleticli/ui/Message.java
  text-ui-test/EXPECTED.TXT
Labels: Sleep

#309 Add JUnit tests for SleepGoal and SleepGoalList
  src/main/java/athleticli/commands/sleep/EditSleepCommand.java
  src/main/java/athleticli/data/sleep/SleepGoal.java
  src/main/java/athleticli/ui/Message.java
  src/test/java/athleticli/commands/sleep/AddSleepCommandTest.java
  src/test/java/athleticli/commands/sleep/EditSleepCommandTest.java
  src/test/java/athleticli/commands/sleep/EditSleepGoalCommandTest.java
  src/test/java/athleticli/commands/sleep/FindSleepCommandTest.java
  src/test/java/athleticli/commands/sleep/ListSleepCommandTest.java
  src/test/java/athleticli/commands/sleep/ListSleepGoalCommandTest.java
  src/test/java/athleticli/commands/sleep/SetSleepGoalCommandTest.java
  src/test/java/athleticli/data/sleep/SleepGoalListTest.java
  src/test/java/athleticli/data/sleep/SleepGoalTest.java
  text-ui-test/EXPECTED.TXT
Labels: priority.High, severity.Medium, type.Bug, type.Task, Sleep

#333 DG Update
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/images/ParserClassDiagram.png
  docs/images/editDietSequenceDiagram.png
  docs/puml/Diet/EditDietSequenceDiagram.puml
  docs/puml/General/ParserClassDiagram.puml
Labels: priority.High, DG

#335 Update Jekyll remote theme
  docs/_config.yml
Labels: priority.Medium, UG, DG

#336 Update About Us
  docs/AboutUs.md
  docs/team/photo/alwo223-github.png
  docs/team/photo/dadevchia-github.png
  docs/team/photo/nihalzp-github.png
Labels: priority.Medium, type.Task, PPP

#337 Update DG
  docs/DeveloperGuide.md
  docs/images/architectureDiagram.svg
  docs/puml/architectureDiagram.puml
Labels: priority.Medium, type.Task, DG

#338 Refactor SleepList and SleepGoalList tests
  src/main/java/athleticli/data/sleep/SleepList.java
  src/test/java/athleticli/data/sleep/SleepGoalListTest.java
  src/test/java/athleticli/data/sleep/SleepGoalTest.java
  src/test/java/athleticli/data/sleep/SleepListTest.java
  src/test/java/athleticli/parser/SleepParserTest.java
Labels: priority.Medium, type.Task, Sleep

#339 Changes to UG, DG and PPP and JavaDoc comments for test classes
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/team/alwo223.md
  docs/team/johndoe.md
  src/main/java/athleticli/data/activity/Swim.java
  src/main/java/athleticli/parser/ActivityParser.java
  src/main/java/athleticli/ui/Message.java
  src/test/java/athleticli/commands/activity/AddActivityCommandTest.java
  src/test/java/athleticli/commands/activity/DeleteActivityCommandTest.java
  src/test/java/athleticli/commands/activity/EditActivityCommandTest.java
  src/test/java/athleticli/commands/activity/FindActivityCommandTest.java
  src/test/java/athleticli/commands/activity/ListActivityCommandTest.java
  src/test/java/athleticli/data/activity/ActivityGoalListTest.java
  src/test/java/athleticli/data/activity/ActivityGoalTest.java
  src/test/java/athleticli/data/activity/ActivityListTest.java
  src/test/java/athleticli/data/activity/ActivityTest.java
  src/test/java/athleticli/data/activity/CycleTest.java
  src/test/java/athleticli/data/activity/RunTest.java
  src/test/java/athleticli/data/activity/SwimTest.java
  src/test/java/athleticli/parser/ActivityParserTest.java
Labels: priority.High, Activity, UG, DG, PPP

#341 Fix url for Alex and Nihal's PPP
  docs/AboutUs.md
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/team/alwo223.md
Labels: PPP

#344 DG Update with Other Activity Goal
  docs/AboutUs.md
  docs/DeveloperGuide.md
  text-ui-test/EXPECTED.TXT
  text-ui-test/input.txt
Labels: priority.High, Activity, Goal, DG

#345 Add manual testing instructions for misc commands
  docs/DeveloperGuide.md
Labels: priority.High, type.Task, DG

#347 Update the Expected Outcome for find-diet
  docs/DeveloperGuide.md
Labels: Diet, DG

#349 Update DG section in Activity Management
  docs/DeveloperGuide.md
  docs/images/AddActivity.svg
  docs/images/AddActivityGoal.svg
Labels: priority.High, Activity, Goal, DG

#351 Replace "Github" with "GitHub"
  docs/AboutUs.md
Labels: priority.Medium, type.Task

#352 Add unique anchor for duplicate headline linking in PPP
  docs/team/alwo223.md
Labels: PPP

#354 Fix links to UG and DG in PPP
  docs/team/alwo223.md
Labels: PPP

#356 Shorten PPP
  docs/team/alwo223.md
Labels: PPP

#358 Update README.md
  README.md
Labels: priority.Medium, type.Task

#359 Add sleep command and sleep list feature to Developers Guide
  docs/DeveloperGuide.md
  docs/images/EditSleepObjectSequenceDiagram.svg
  docs/images/SleepAndSleepListClassDiagram.svg
  docs/puml/Sleep/SleepAndSleeplistClassDiagram.puml
  docs/puml/Sleep/SleepObjectSequenceDiagram.puml
  docs/team/dadevchia.md
Labels: Sleep, DG

#361 Fix DG numbering
  docs/DeveloperGuide.md
Labels: DG

#363 Minor update to UG
  docs/UserGuide.md
Labels: UG

#364 Replace 'command' with `command` in DG
  docs/DeveloperGuide.md
Labels: DG

#365 PPP Update
  docs/team/nihalzp.md
Labels: priority.High, PPP

#366 PPP Update - Fix Page Layout
  docs/team/nihalzp.md
Labels: PPP
