Repository AY2324S1-CS2113-T17-1/tp, pull requests merged in 2023-10, with the labels that each got.

#8 Add CLI interaction
  build.gradle
  src/main/java/athleticli/AthletiCLI.java
  src/main/java/athleticli/commands/ByeCommand.java
  src/main/java/athleticli/commands/Command.java
  src/main/java/athleticli/commands/activity/AddActivityCommand.java
  src/main/java/athleticli/commands/activity/DeleteActivityCommand.java
  src/main/java/athleticli/commands/activity/EditActivityCommand.java
  src/main/java/athleticli/commands/activity/ListActivityCommand.java
  src/main/java/athleticli/commands/diet/AddMealCommand.java
  src/main/java/athleticli/commands/diet/DeleteMealCommand.java
  src/main/java/athleticli/commands/diet/EditDietGoalCommand.java
  src/main/java/athleticli/commands/diet/ListMealCommand.java
  src/main/java/athleticli/commands/diet/SetDietGoalCommand.java
  src/main/java/athleticli/commands/sleep/AddSleepCommand.java
  src/main/java/athleticli/commands/sleep/DeleteSleepCommand.java
  src/main/java/athleticli/commands/sleep/EditSleepCommand.java
  src/main/java/athleticli/commands/sleep/ListSleepCommand.java
  src/main/java/athleticli/commands/sleep/ListSleepGoalCommand.java
  src/main/java/athleticli/commands/sleep/SetSleepGoalCommand.java
  src/main/java/athleticli/data/Data.java
  src/main/java/athleticli/data/activity/Activity.java
  src/main/java/athleticli/data/activity/ActivityGoal.java
  src/main/java/athleticli/data/activity/ActivityGoalList.java
  src/main/java/athleticli/data/activity/ActivityList.java
  src/main/java/athleticli/data/diet/DietGoal.java
  src/main/java/athleticli/data/diet/DietGoalList.java
  src/main/java/athleticli/data/diet/Meal.java
  src/main/java/athleticli/data/diet/MealList.java
  src/main/java/athleticli/data/sleep/Sleep.java
  src/main/java/athleticli/data/sleep/SleepGoal.java
  src/main/java/athleticli/data/sleep/SleepGoalList.java
  src/main/java/athleticli/data/sleep/SleepList.java
  src/main/java/athleticli/exceptions/AthletiException.java
  src/main/java/athleticli/exceptions/UnknownCommandException.java
  src/main/java/athleticli/ui/CommandName.java
  src/main/java/athleticli/ui/Message.java
  src/main/java/athleticli/ui/Parser.java
  src/main/java/athleticli/ui/Ui.java
  src/main/java/seedu/duke/Duke.java
  src/test/java/athleticli/ui/ParserTest.java
  src/test/java/seedu/duke/DukeTest.java
  text-ui-test/EXPECTED.TXT
  text-ui-test/input.txt
Labels: priority.High

#17 Add DietGoal Class and DietGoalList Class
  src/main/java/athleticli/dietgoal/DietGoal.java
  src/main/java/athleticli/dietgoal/DietGoalList.java
  src/test/java/athleticli/ui/dietgoal/DietGoalListTest.java
  src/test/java/athleticli/ui/dietgoal/DietGoalTest.java
Labels: priority.High

#19 Add Activity
  docs/README.md
  src/main/java/athleticli/commands/activity/AddActivityCommand.java
  src/main/java/athleticli/data/Data.java
  src/main/java/athleticli/data/activity/Activity.java
  src/main/java/athleticli/data/activity/Cycle.java
  src/main/java/athleticli/data/activity/Run.java
  src/main/java/athleticli/data/activity/Swim.java
  src/main/java/athleticli/exceptions/EmptyArgumentException.java
  src/main/java/athleticli/ui/CommandName.java
  src/main/java/athleticli/ui/Message.java
  src/main/java/athleticli/ui/Parser.java
  src/test/java/athleticli/commands/activity/AddActivityCommandTest.java
  src/test/java/athleticli/data/activity/ActivityTest.java
  src/test/java/athleticli/data/activity/CycleTest.java
  src/test/java/athleticli/data/activity/RunTest.java
  src/test/java/athleticli/data/activity/SwimTest.java
Labels: priority.High

#31 Diet parser
  docs/README.md
  src/main/java/athleticli/commands/diet/AddDietCommand.java
  src/main/java/athleticli/commands/diet/AddMealCommand.java
  src/main/java/athleticli/commands/diet/DeleteDietCommand.java
  src/main/java/athleticli/commands/diet/DeleteMealCommand.java
  src/main/java/athleticli/commands/diet/ListDietCommand.java
  src/main/java/athleticli/commands/diet/ListMealCommand.java
  src/main/java/athleticli/data/diet/DietGoalList.java
  src/main/java/athleticli/data/diet/DietList.java
  src/main/java/athleticli/ui/CommandName.java
  src/main/java/athleticli/ui/Message.java
  src/main/java/athleticli/ui/Parser.java
  src/test/java/athleticli/commands/diet/AddDietCommandTest.java
  src/test/java/athleticli/commands/diet/DeleteDietCommandTest.java
  src/test/java/athleticli/commands/diet/ListDietCommandTest.java
  src/test/java/athleticli/data/diet/DietListTest.java
  src/test/java/athleticli/ui/ParserTest.java
Labels: priority.High, type.Story

#41 Use `AthletiException` class to handle all exceptions
  src/main/java/athleticli/exceptions/EmptyArgumentException.java
  src/main/java/athleticli/exceptions/UnknownCommandException.java
  src/main/java/athleticli/ui/Message.java
  src/main/java/athleticli/ui/Parser.java
  src/test/java/athleticli/ui/ParserTest.java
Labels: priority.Medium

#44 Use `assert` and `logging`
  src/main/java/athleticli/AthletiCLI.java
  src/main/java/athleticli/ui/Parser.java
  src/main/java/athleticli/ui/Ui.java
Labels: priority.Medium

#51 Added improvements to sleep feature
  docs/README.md
  src/main/java/athleticli/commands/sleep/AddSleepCommand.java
  src/main/java/athleticli/commands/sleep/DeleteSleepCommand.java
  src/main/java/athleticli/commands/sleep/EditSleepCommand.java
  src/main/java/athleticli/commands/sleep/ListSleepCommand.java
  src/main/java/athleticli/data/Data.java
  src/main/java/athleticli/data/sleep/Sleep.java
  src/main/java/athleticli/data/sleep/SleepList.java
  src/main/java/athleticli/ui/Message.java
  src/main/java/athleticli/ui/Parser.java
  src/test/java/athleticli/commands/sleep/AddSleepCommandTest.java
  src/test/java/athleticli/commands/sleep/DeleteSleepCommandTest.java
  src/test/java/athleticli/commands/sleep/EditSleepCommandTest.java
  src/test/java/athleticli/commands/sleep/ListSleepCommandTest.java
  src/test/java/athleticli/data/sleep/SleepListTest.java
  src/test/java/athleticli/data/sleep/SleepTest.java
  src/test/java/athleticli/ui/ParserTest.java
Labels: type.Optimization

#59 Implement commands for editing, deleting, viewing activities
  docs/README.md
  src/main/java/athleticli/commands/activity/AddActivityCommand.java
  src/main/java/athleticli/commands/activity/DeleteActivityCommand.java
  src/main/java/athleticli/commands/activity/EditActivityCommand.java
  src/main/java/athleticli/commands/activity/ListActivityCommand.java
  src/main/java/athleticli/data/activity/Activity.java
  src/main/java/athleticli/data/activity/Cycle.java
  src/main/java/athleticli/data/activity/Run.java
  src/main/java/athleticli/data/activity/Swim.java
  src/main/java/athleticli/ui/CommandName.java
  src/main/java/athleticli/ui/Message.java
  src/main/java/athleticli/ui/Parameter.java
  src/main/java/athleticli/ui/Parser.java
  src/test/java/athleticli/data/activity/ActivityTest.java
  src/test/java/athleticli/data/activity/CycleTest.java
  src/test/java/athleticli/data/activity/RunTest.java
  src/test/java/athleticli/data/activity/SwimTest.java
Labels: priority.High, type.Story

#66 Fix User Guide for Diet and Reformat
  docs/README.md
  src/main/java/athleticli/ui/Message.java
Labels: priority.High

#77 Add `help` command
  src/main/java/athleticli/commands/HelpCommand.java
  src/main/java/athleticli/ui/CommandName.java
  src/main/java/athleticli/ui/Message.java
  src/main/java/athleticli/ui/Parser.java
  text-ui-test/EXPECTED.TXT
  text-ui-test/runtest.bat
  text-ui-test/runtest.sh
Labels: priority.Medium, type.Task

#67 Add user guide for diet goals
  docs/README.md
Labels: priority.High

#79 Add storage features
  .gitignore
  src/main/java/athleticli/AthletiCLI.java
  src/main/java/athleticli/commands/ByeCommand.java
  src/main/java/athleticli/commands/HelpCommand.java
  src/main/java/athleticli/commands/SaveCommand.java
  src/main/java/athleticli/data/Data.java
  src/main/java/athleticli/data/activity/Activity.java
  src/main/java/athleticli/data/activity/ActivityGoal.java
  src/main/java/athleticli/data/activity/ActivityGoalList.java
  src/main/java/athleticli/data/activity/ActivityList.java
  src/main/java/athleticli/data/activity/Cycle.java
  src/main/java/athleticli/data/activity/Run.java
  src/main/java/athleticli/data/activity/Swim.java
  src/main/java/athleticli/data/diet/Diet.java
  src/main/java/athleticli/data/diet/DietGoal.java
  src/main/java/athleticli/data/diet/DietGoalList.java
  src/main/java/athleticli/data/diet/DietList.java
  src/main/java/athleticli/data/sleep/Sleep.java
  src/main/java/athleticli/data/sleep/SleepGoal.java
  src/main/java/athleticli/data/sleep/SleepGoalList.java
  src/main/java/athleticli/data/sleep/SleepList.java
  src/main/java/athleticli/storage/Config.java
  src/main/java/athleticli/storage/Storage.java
  src/main/java/athleticli/ui/CommandName.java
  src/main/java/athleticli/ui/Message.java
  src/main/java/athleticli/ui/Parser.java
  text-ui-test/EXPECTED.TXT
Labels: priority.High, type.Task

#76 Sleep Improvements
  src/main/java/athleticli/commands/sleep/AddSleepCommand.java
  src/main/java/athleticli/commands/sleep/DeleteSleepCommand.java
  src/main/java/athleticli/commands/sleep/EditSleepCommand.java
  src/main/java/athleticli/commands/sleep/ListSleepCommand.java
  src/main/java/athleticli/data/sleep/SleepList.java
  src/main/java/athleticli/ui/Parameter.java
  src/main/java/athleticli/ui/Parser.java
  src/test/java/athleticli/commands/sleep/AddSleepCommandTest.java
  src/test/java/athleticli/commands/sleep/EditSleepCommandTest.java
  src/test/java/athleticli/commands/sleep/ListSleepCommandTest.java
  src/test/java/athleticli/data/sleep/SleepListTest.java
  src/test/java/athleticli/ui/ParserTest.java
  text-ui-test/EXPECTED.TXT
  text-ui-test/input.txt
Labels: priority.Medium, type.Optimization

#88 Add `Findable` interface and classes for find commands
  src/main/java/athleticli/commands/FindCommand.java
  src/main/java/athleticli/commands/HelpCommand.java
  src/main/java/athleticli/commands/activity/FindActivityCommand.java
  src/main/java/athleticli/commands/diet/FindDietCommand.java
  src/main/java/athleticli/commands/sleep/FindSleepCommand.java
  src/main/java/athleticli/data/Findable.java
  src/main/java/athleticli/data/activity/ActivityList.java
  src/main/java/athleticli/data/diet/DietList.java
  src/main/java/athleticli/data/sleep/SleepList.java
  src/main/java/athleticli/ui/CommandName.java
  src/main/java/athleticli/ui/Message.java
  src/main/java/athleticli/ui/Parser.java
  text-ui-test/EXPECTED.TXT
Labels: priority.High

#91 Prevent tracking of negative distances and adjust duration input format
  docs/README.md
  src/main/java/athleticli/data/activity/Activity.java
  src/main/java/athleticli/data/activity/Cycle.java
  src/main/java/athleticli/data/activity/Run.java
  src/main/java/athleticli/data/activity/Swim.java
  src/main/java/athleticli/ui/Message.java
  src/main/java/athleticli/ui/Parser.java
  src/test/java/athleticli/commands/activity/AddActivityCommandTest.java
  src/test/java/athleticli/data/activity/ActivityTest.java
  src/test/java/athleticli/data/activity/CycleTest.java
  src/test/java/athleticli/data/activity/RunTest.java
  src/test/java/athleticli/data/activity/SwimTest.java
Labels: priority.High, severity.Low, type.Bug, Activity

#92 Implement find by date and timespan filtering of activities
  docs/README.md
  src/main/java/athleticli/commands/activity/AddActivityCommand.java
  src/main/java/athleticli/data/activity/ActivityGoal.java
  src/main/java/athleticli/data/activity/ActivityList.java
  src/main/java/athleticli/ui/CommandName.java
  src/test/java/athleticli/data/activity/ActivityListTest.java
  text-ui-test/EXPECTED.TXT
Labels: priority.High, type.Story, Activity

#95 Implement goal abstract class for goal functionality
  src/main/java/athleticli/data/Goal.java
Labels: priority.High, Goal

#98 Remove files that shouldn't be tracked
  .gitignore
  .vscode/settings.json
  text-ui-test/data/athleticli.bin
Labels: priority.Medium, type.Optimization

#100 Add `Data data` as a parameter of `isAchieved`
  src/main/java/athleticli/AthletiCLI.java
  src/main/java/athleticli/data/Goal.java
  src/main/java/athleticli/ui/Ui.java
Labels: priority.High, type.Optimization, Goal

#102 Diet time tracking + find-diet
  docs/README.md
  src/main/java/athleticli/commands/diet/DeleteDietCommand.java
  src/main/java/athleticli/commands/diet/FindDietCommand.java
  src/main/java/athleticli/data/diet/Diet.java
  src/main/java/athleticli/data/diet/DietList.java
  src/main/java/athleticli/ui/Message.java
  src/main/java/athleticli/ui/Parameter.java
  src/main/java/athleticli/ui/Parser.java
  src/test/java/athleticli/commands/diet/AddDietCommandTest.java
  src/test/java/athleticli/commands/diet/DeleteDietCommandTest.java
  src/test/java/athleticli/commands/diet/ListDietCommandTest.java
  src/test/java/athleticli/data/diet/DietListTest.java
  src/test/java/athleticli/data/diet/DietTest.java
  src/test/java/athleticli/ui/ParserTest.java
  text-ui-test/EXPECTED.TXT
  text-ui-test/input.txt
Labels: priority.High, type.Enhancement, type.Story, type.Task, Diet

#105 Expand DG and beautify website
  docs/.gitignore
  docs/AboutUs.md
  docs/DeveloperGuide.md
  docs/Gemfile
  docs/README.md
  docs/UserGuide.md
  docs/UserGuideTmp.md
  docs/_config.yml
Labels: priority.Medium, type.Task

#106 Diet Edit Feature
  docs/UserGuide.md
  docs/UserGuideTmp.md
  src/main/java/athleticli/commands/HelpCommand.java
  src/main/java/athleticli/commands/diet/EditDietCommand.java
  src/main/java/athleticli/ui/CommandName.java
  src/main/java/athleticli/ui/Message.java
  src/main/java/athleticli/ui/Parser.java
  src/test/java/athleticli/commands/diet/EditDietCommandTest.java
  src/test/java/athleticli/ui/ParserTest.java
  text-ui-test/EXPECTED.TXT
  text-ui-test/input.txt
Labels: priority.High, type.Story, type.Task, Diet

#107 Developer Guide for Diet
  docs/DeveloperGuide.md
Labels: type.Task, Diet

#109 Reimplement `Goal` abstract class
  src/main/java/athleticli/data/Goal.java
Labels: priority.High, type.Task, Goal

#113 Activity Goal functionality and add command
  docs/DeveloperGuide.md
  docs/DeveloperGuide/AddActivity.png
  docs/DeveloperGuide/AddActivity.puml
  docs/README.md
  src/main/java/athleticli/commands/activity/SetActivityGoalCommand.java
  src/main/java/athleticli/data/Goal.java
  src/main/java/athleticli/data/activity/ActivityGoal.java
  src/main/java/athleticli/data/activity/ActivityList.java
  src/main/java/athleticli/ui/CommandName.java
  src/main/java/athleticli/ui/Message.java
  src/main/java/athleticli/ui/Parameter.java
  src/main/java/athleticli/ui/Parser.java
  src/test/java/athleticli/commands/activity/SetActivityGoalCommandTest.java
  src/test/java/athleticli/data/activity/ActivityGoalTest.java
  src/test/java/athleticli/data/activity/ActivityListTest.java
  src/test/java/athleticli/ui/ParserTest.java
  text-ui-test/EXPECTED.TXT
  text-ui-test/input.txt
Labels: priority.High, type.Story, Activity, Goal, Find

#114 Added sleep features to Developer Guide
  docs/DeveloperGuide.md
Labels: priority.High, Sleep

#116 Reimplement storage features
  src/main/java/athleticli/AthletiCLI.java
  src/main/java/athleticli/commands/SaveCommand.java
  src/main/java/athleticli/data/Data.java
  src/main/java/athleticli/data/Goal.java
  src/main/java/athleticli/data/StorableList.java
  src/main/java/athleticli/data/activity/Activity.java
  src/main/java/athleticli/data/activity/ActivityGoal.java
  src/main/java/athleticli/data/activity/ActivityGoalList.java
  src/main/java/athleticli/data/activity/ActivityList.java
  src/main/java/athleticli/data/activity/Cycle.java
  src/main/java/athleticli/data/activity/Run.java
  src/main/java/athleticli/data/activity/Swim.java
  src/main/java/athleticli/data/diet/Diet.java
  src/main/java/athleticli/data/diet/DietGoal.java
  src/main/java/athleticli/data/diet/DietGoalList.java
  src/main/java/athleticli/data/diet/DietList.java
  src/main/java/athleticli/data/sleep/Sleep.java
  src/main/java/athleticli/data/sleep/SleepGoal.java
  src/main/java/athleticli/data/sleep/SleepGoalList.java
  src/main/java/athleticli/data/sleep/SleepList.java
  src/main/java/athleticli/exceptions/WrappedIOException.java
  src/main/java/athleticli/storage/Config.java
  src/main/java/athleticli/storage/Storage.java
Labels: priority.High, type.Task

#121 Rename `Timespan` to `TimeSpan`
  src/main/java/athleticli/data/Goal.java
  src/main/java/athleticli/data/activity/ActivityGoal.java
  src/main/java/athleticli/data/activity/ActivityList.java
  src/main/java/athleticli/ui/Parser.java
  src/test/java/athleticli/commands/activity/SetActivityGoalCommandTest.java
  src/test/java/athleticli/data/activity/ActivityGoalTest.java
  src/test/java/athleticli/data/activity/ActivityListTest.java
  src/test/java/athleticli/ui/ParserTest.java
Labels: priority.Medium, type.Optimization, Goal

#125 Update activity section of UserGuide
  docs/UserGuide.md
Labels: priority.High, type.Task, Activity

#128 Handle parsing exceptions in `load`
  src/main/java/athleticli/AthletiCLI.java
  src/main/java/athleticli/data/Data.java
  src/main/java/athleticli/data/StorableList.java
  src/main/java/athleticli/exceptions/WrappedAthletiException.java
  src/main/java/athleticli/storage/Storage.java
  src/main/java/athleticli/ui/Message.java
Labels: priority.High, type.Task

#130 Activity Goals - Edit, List + Other Improvements
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/java/athleticli/commands/activity/EditActivityGoalCommand.java
  src/main/java/athleticli/commands/activity/ListActivityGoalCommand.java
  src/main/java/athleticli/data/activity/ActivityGoalList.java
  src/main/java/athleticli/ui/CommandName.java
  src/main/java/athleticli/ui/Message.java
  src/main/java/athleticli/ui/Parser.java
  src/test/java/athleticli/commands/activity/EditActivityGoalCommandTest.java
  src/test/java/athleticli/commands/activity/ListActivityGoalCommandTest.java
Labels: priority.High, type.Story, type.Task, Diet, Activity, Goal
